config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :web_sites, except: [:index] do 
    member do
      post :send_mail
    end
    collection do
      match :preview, via: [:get, :post]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/framework.rb
class Framework < ApplicationRecord

  has_many :templates
  has_many :web_sites


end

app/models/template.rb
class Template < ApplicationRecord

  belongs_to :framework
  has_many :wes_sites


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :web_sites
end

app/models/web_site.rb
class WebSite < ApplicationRecord

  belongs_to :user
  belongs_to :template, optional: true
  belongs_to :framework, optional: true

  validates :name, :email, presence: true

  after_create :create_hmac

  def create_hmac
    key = Rails.application.credentials.secret_key_base
    data = self.id.to_s
    self.hmac = OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), key, data)
    self.save
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @web_sites = current_user.web_sites.order(id: :asc)
  end

end

app/controllers/web_sites_controller.rb
class WebSitesController < ApplicationController
  before_action :authenticate_user!, except: [:preview, :send_mail]
  skip_before_action :verify_authenticity_token, only: [:preview, :send_mail]
  before_action :set_web_site, except: [:preview, :send_mail]


  def new
    @templates = Template.all
  end

  def create
    @web_site = current_user.web_sites.new(web_site_params)
    respond_to do |format|
      if @web_site.save
        flash[:success] = "Guardado correctamente"
        format.html{ redirect_to root_path }
      else
        format.html{ render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @web_site.update_attributes(web_site_params)
        flash[:success] = "Guardado correctamente"
        format.html{ redirect_to root_path }
      else
        format.html{ render :new }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @web_site.destroy
        flash[:success] = "Eliminado correctamente"
        format.html{ redirect_to root_path }
      else
        format.html{ render :index }
      end
    end
  end

  def preview
    web_site = WebSite.find_by(hmac: params[:id]) rescue nil
    @id = params[:id]
    @js = web_site.js rescue params[:js]
    @css = web_site.css rescue params[:css]
    @html = web_site.html rescue params[:html]
    @framework = web_site.framework rescue (Framework.find(params[:framework]) rescue nil)
    render layout: false
  end

  def send_mail
    web_site = WebSite.find_by(hmac: params[:id]) rescue nil
    parameters = params.except(:controller, :action, :id)
    PreviewMailer.send_mail(web_site.email, parameters).deliver_now
    render plain: t(:message_send)
  end

  private
  def set_web_site
    @web_site = WebSite.find(params[:id]) rescue WebSite.new
  end

  def web_site_params
    params.require(:web_site).permit(
      :name,
      :email,
      :description,
      :css,
      :html,
      :js,
      :template_id,
      :framework_id
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_modal_preview.html.haml
.modal.fade#modal{tambindex: '-1', role: 'dialog'}
  .modal-dialog.modal-lg.modal-dialog-centered{role: 'document'}
    .modal-content
      .modal-header
        %h5.modal-title=t(:preview)
        %button.close{type: 'button', 'data-dismiss' => 'modal', 'aria-label' => 'Close'}
          %span{'aria-hidden' => true} &times;
      .modal-body
        .row
          .col-12
            %label=t(:code_for_your_page)
            %textarea#embeed.form-control{rows: 3, readonly: true, style: 'resize: none;'}
          &nbsp;
          %iframe#iframe.col-12{frameborder: 0}
      .modal-footer
        %button.btn.btn-outline-secondary{type: 'button', 'data-dismiss' => 'modal'}=t(:close)

app/views/home/index.html.haml
.card
  .card-header.clearfix
    .float-right
      =link_to t(:new_web_site), new_web_site_path
  .card-body
    %table.table.table-bordered.table-striped
      %thead
        %tr
          %th=t(:name)
          %th=t(:description)
          %th=t(:email)
          %th=t(:actions)
      %tbody
        -@web_sites.each do |web_site|
          %tr
            %td=web_site.name
            %td=web_site.description
            %td=web_site.email
            %td
              %a{href: "javascript:show_preview('#{web_site.hmac}')"}=t(:preview)
              =link_to t(:edit), edit_web_site_path(web_site)
              =link_to t(:delete), web_site_path(web_site), method: :DELETE, data: { confirm: t(:confirm)}
=render 'modal_preview'
:javascript
  function show_preview(id){
    var url = "#{preview_web_sites_url()}";
    url = url+'?id='+id;
    console.log(url);
    $('#iframe').attr('src', url);
    $('#embeed').val("<iframe src='"+url+"' frameborder='0' ></iframe>");
    $('#modal').modal('show');
  }

app/views/layouts/_messages.html.haml
-flash.each do |key, value|
  -key = "warning" if key == "alert"
  -key = "success" if key == "notice"
  .alert.alert-dismissible.fade.show.flash-message{role: "alert", class: "alert-#{key}"}
    =value
    %button.close{type: "button", "data-dismiss"=>"alert", "aria-label"=>"Close" }
      %span{"aria-hidden"=>"true"}
        &times;

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %button.navbar-toggler{"aria-controls" => "navbarTogglerTitle", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarTogglerTitle", "data-toggle" => "collapse", type: "button"}
    %span.navbar-toggler-icon
  %a.navbar-brand{href: root_path}=t(:app_name)
  #navbarTogglerTitle.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto.mt-2.mt-lg-0
      %li.nav-item.active
        %a.nav-link{href: root_path}=t(:home)
      %li.nav-item
        %a.nav-link{href: "#"}=t(:config)
    %form.form-inline.my-2.my-lg-0
      =link_to t(:sign_out), destroy_user_session_path, method: :delete, class: "btn btn-outline-danger my-2 my-sm-0"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ExternalEmailForm
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -if user_signed_in?
      =render 'layouts/navbar'
      
    =render 'layouts/messages'
    .container
      =yield

app/views/layouts/maintenance.html.erb
<!DOCTYPE html> 
  <html>
  <head>
    <title>Mantenimiento</title>
    <style type="text/css">
      body {
        width: 400px;
        margin: 100px auto;
        font: 300 120% "OpenSans", "Helvetica Neue", "Helvetica", Arial, Verdana, sans-serif;
      }
      h1 {
        font-weight: 300;
      }
    </style>
  </head>
  <body>
    <h1>Mantenimiento</h1>
    <p>
      Sitio deshabilitado por <%= reason ? reason : "mantenimiento" %>
      <br>
      desde <%= Time.now.strftime("%F %H:%M %Z") %>.
    </p>
    <p>Volveremos <%= deadline ? deadline : "pronto" %>.</p> 
  </body>
</html>

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to t(:log_in), new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to t(:sign_up), new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to t(:forgot_your_password?), new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/web_sites/_form.html.haml
=simple_form_for @web_site do |f|
  .card
    .card-body
      .row
        .col-6
          =f.input :name
        .col-6
          =f.input :email
        .col-6
          =f.input :description
        .col-6
          =f.association :template
        .col-12
          =f.association :framework
        .col-12
          =f.input :css, input_html: { class: 'editor', rows: 6 }
        .col-12
          =f.input :js, input_html: { class: 'editor', rows: 6 }
        .col-12
          =f.input :html, input_html: { class: 'editor', rows: 6 }
        .col-12
          %h5=t(:preview)
          %iframe#preview.w-100
    .card-footer.clearfix
      .float-right
        =link_to t(:return), root_path, class: "btn btn-outline-warning"
        =f.button :submit, class: "btn btn-success"
:javascript

  var templates = #{@templates.to_json.html_safe};

  $(document).ready(function(){
    reload_preview();

    $('.editor').on('focusout', function(){
      reload_preview();
    });
    $('#web_site_template_id').on('change', function(){
      var id_sel = this.value;
      var template = null;
      $.each(templates, function(index, temp){
        if(temp.id == id_sel){template = temp;} 
      });
      $('#web_site_framework_id').val(template.framework_id);
      $('#web_site_css').val(template.css);
      $('#web_site_html').val(template.html);
      $('#web_site_js').val(template.js);
      reload_preview();
    });
    $('#web_site_framework_id').on('change', function(){
      reload_preview();
    });
  });

  function reload_preview(){
    $.ajax({
      url: "#{preview_web_sites_path()}",
      type: "post",
      data: {
        "js": $('#web_site_js').val(),
        "css": $('#web_site_css').val(),
        "html": $('#web_site_html').val(),
        "framework": $('#web_site_framework_id').val()
      },
      success: function(data) {
        var iframe = document.getElementById('preview');
        iframe.contentDocument.write(data);
        iframe.contentWindow.document.close();
      },
      error: function(data) {
        console.log('error');
      }
    });
  }

app/views/web_sites/_preview.html.haml
-if !@framework.nil?
  =@framework.css.html_safe rescue ''
  =@framework.js.html_safe rescue ''
%style
  =@css.html_safe
%script
  window.onload = function(){#{@js.html_safe}}
-if @id.blank?
  =@html.html_safe
-else
  %form#form{action: send_mail_web_site_url(@id), method: 'post'}
    =@html.html_safe

app/views/web_sites/edit.html.haml
=render 'form'

app/views/web_sites/new.html.haml
=render 'form'

app/views/web_sites/preview.html.haml
=render 'preview'

app/views/web_sites/preview_form.html.haml
=render 'preview'